### ISSUE TITLE
Impossible to sign up new members in loyalty shop

### ISSUE THREAD

**Issue by PierreFritsch** [SAP/yaas-loyalty-storefront#1]
Hi colleagues,

On a loyalty storefront set up by following the application guide, new members can't sign up for the loyalty program. An error appears in the Console (using Chrome, on Mac):

```
angular.js:12416 TypeError: Cannot read property 'analytics' of undefined
    at Object.getHybrisProfileAnalyticsUrl (store.min.js:12051)
    at Object.checkForHybrisProfileSubscription (store.min.js:11630)
    at Scope.$scope.registerCustomerForProgram (store.min.js:12940)
    at Scope.$scope.getLoyaltyProgramMembership (store.min.js:12992)
    at fn (eval at compile (angular.js:13231), <anonymous>:4:272)
    at angular-touch.js:472
    at Scope.$eval (angular.js:15878)
    at Scope.$apply (angular.js:15978)
    at HTMLButtonElement.<anonymous> (angular-touch.js:471)
    at HTMLButtonElement.dispatch (jquery.js:4435)
```

Maybe this is related to the 403 error which appears a few lines above?

```
https://api.yaas.io/hybris/profile-edge/v1/events Failed to load resource: the server responded with a status of 403 (Forbidden)
```

If I am required to subscribe to SAP Hybris Profile packages to use this storefront, then I feel that the documentation should mention it.

Background information:
- I followed the instructions from the application guide and from the README file on this repository to set up a tenant and a loyalty storefront. Then I started the storefront using `grunt prepare:mystorefront` and `grunt run:mystorefront` and I accessed http://localhost:9099/mystorefronttenant. 
- I clicked "SIGN IN" and selected "CREATE ACCOUNT" without checking the box "Sign me up for MyLoyaltyProgram to earn welcome points".
- On the "My Account" page, I clicked the button "SIGN UP FOR MyLoyaltyProgram". Nothing happened (and no new entry appeared in the Members builder module under Loyalty), so I checked the console. 

Best regards
Pierre

**Comment by ghost** [comment]
Hi Pierre Fritsch,
Thank you for pointing it out, the url file had required entry missing.
